# Generated by Django 2.2 on 2019-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190403_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='full_name',
            field=models.CharField(default='not set, edit now?', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='present_address',
            field=models.CharField(default='not set, edit now?', max_length=255),
            preserve_default=False,
        ),
    ]
